# -*- coding: utf-8 -*-
"""Exercicio_DATAFRAME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6NZJyDvZwX7YEpK8LZKY0vGTtp3wpVg
"""

import pandas as pd
vendas = pd.read_excel('Vendas.xlsx')
# print(vendas)

vendas.head()

print(vendas.dtypes)

vendasLoja = vendas.groupby('ID Loja')['Valor Final'].sum()
vendasLoja = vendasLoja.sort_values(ascending=False)
print(vendasLoja)

vendasQuantidade = vendas.groupby('ID Loja')['Quantidade'].sum()
vendasQuantidade = vendasQuantidade.sort_values(ascending=False)
print(vendasQuantidade)

maisVendida = vendas.sort_values(by='Quantidade', ascending=False)
maisVendida.head(10)

vendasFiltro = vendas.groupby('Produto')['Quantidade'].sum()
maisVendido = vendasFiltro.sort_values(ascending=False).head()
print(maisVendido)

#Com essa breve analise podemos ver que a bermuda mais vendida e a lisa, e poderia focar mais nas vendas desse produto em especifico e focar menos na bermuda estampada
