# -*- coding: utf-8 -*-
"""senai_python_aula8_DATAFRAME

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYvJdJdtiWffHu9u946Nze73oLpc9FRT
"""

import pandas as pd

serie = pd.Series(["Carol", "Jessica", "Caique", "Artur"])
print(serie)

serie[1]

serie[[0,3]]

serie[1:3]

serie.info()

serie.describe()

serie = pd.Series(["Carol", "Jessica", "Caique", "Artur"], index = ["a", "b", "c", "d"])
print(serie)

serie.array

serie.index

serie = pd.Series([5,10,15,20,25])
print(serie)
serie[serie<=15]

dicionario = serie.to_dict()
print(dicionario)

populacao = {'Sao Paulo' : 114451,
             'Sao bernado' : 811,
             'Sao Andre' : 749,
             'Sao Caetano' : 162,
             }

serie_pop = pd.Series(populacao)
print(serie_pop)

serie_pop.describe()

populacao = {'Sao Paulo' : 114451,
             'Sao bernado' : 811,
             'Sao Andre' : 749,
             'Sao Caetano' : 162,
             }

cidades = ['Sao Paulo', 'Campinas', 'Sao Bernado', 'Sao Caetano']

serie_pop = pd.Series(populacao, index = cidades)
print(serie_pop)